language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_install:
  - gem update --system
  - gem --version

install:
  - bundle install --path vendor/bundle

before_script:
  - RAILS_ENV=test bundle exec rails db:create