language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development

before_script:
  - bundle exec rake db:create db:migrate db:test:prepare